### ISSUE TITLE
CTE's recursive flag is not preserved when merging

### ISSUE THREAD

**Issue by tavlima** [GeorgeKaraszi/ActiveRecordExtended#35]
The example below doesn't seem to work. Is this by design? If so, could you please explain why?

```ruby
scope :chain_members, -> (starting_node) do 
  baseline_term = Node.where(id: starting_node.id)
  recursive_term = Node.joins('JOIN ancestors ON ancestors.parent_id = nodes.id')
  
  recursive_cte = Node.with.recursive(ancestors: Node.union(baseline_term, recursive_term))

  merge(recursive_cte).joins("INNER JOIN ancestors ON ancestors.id = member.node_id")
end
```

**Comment by GeorgeKaraszi** [comment]
It's on the todo list for dealing with `merge` ... Its (tbh) incomplete due to a few complexities of Rails. In-fact Rails itself doesn't have a good method for merging in complex queries either as a lot of stuff simply gets ignored during the process. 

I have plans to fix this in an upcoming release cycle (unless someone can beat me to it).

**Comment by GeorgeKaraszi** [comment]
New fix has finally been merged into master and will be apart of the next upcoming release.
