### ISSUE TITLE
Weird behavior with column name "notifications"

### ISSUE THREAD

**Issue by manuelmeurer** [GeorgeKaraszi/ActiveRecordExtended#86]
I have a model `User` with an array column "notifications", and when I try to query it like this:

`User.where.any(notifications: "foo")`

the generated SQL is

`SELECT "users".* FROM "users" WHERE NULL = ANY("users"."id")`

If I use any other column name, it works fine:

`User.where.any(whatever: "foo")`

generates

`SELECT "users".* FROM "users" WHERE 'foo' = ANY("users"."whatever")`

Is there something special about the column name "notifications"? 🤔

**Comment by GeorgeKaraszi** [comment]
I think I figured it out. Do you have a relationship with your User model `has_many :notifications` ? I think what's happening is that it's reflecting on the requested column name and aligning that with it. I'll need to see if this is AR or ARE doing since this gem (ARE) uses a lot of ARs where clause parsing and resolving, especially with `where.any`

**Comment by manuelmeurer** [comment]
Yeah, that's it! 😄 I removed the `has_many :notifications` (it was added by a gem) and it works now.
Thanks for figuring it out so quick and let me know if I can help in any way to resolve it.

**Comment by GeorgeKaraszi** [comment]
It's actually not ARE, it's AR. if you did `User.where(notifications: "foo")` you'll end up with the same thing.

**Comment by manuelmeurer** [comment]
Ok yeah, makes sense. I guess it's not advisable to have an association and an attribute/column with the same name. 😸
